### ISSUE TITLE
SDK-style example and nuget packages of tSQLt framework

### ISSUE THREAD

**Issue by cagrin** [tSQLt-org/tSQLt-visual-studio-examples#11]
I tried to use an SDK-style project of SQL Server Data-Tier Application. It feels really natural to use ```dotnet build``` and ```dotnet publish``` thanks to https://github.com/rr-wfm/MSBuild.Sdk.SqlProj

Best part is, that tSQLt framework can be delivered in a very convenient way, as a nuget package.

Example file ```Tests.csproj``` looks like this:

```xml
<Project Sdk="MSBuild.Sdk.SqlProj/2.0.0-beta.1">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <SqlServerVersion>Sql150</SqlServerVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Code\Code.csproj" />
    <PackageReference Include="tSQLt.2019" Version="1.0.7950.1808" />
  </ItemGroup>
</Project>
```
where ```tSQLt.2019``` is a name of nuget package. Yes, we would need a lot of packages for each SqlServerVersion. 

I put the whole example here: https://github.com/cagrin/tSQLt-visual-studio-examples

**What do you think about this SDK-style?
Could it be possible to release nuget packages of tSQLt framework?**

**Comment by lizbaron** [comment]
This sounds like a great idea! We are in the middle of pushing a new release of tSQLt, but would love to take a look at this more closely after that is done.

Copying the nuspec here for future reference.
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>tSQLt.2019</id>
    <version>1.0.7950.1808</version>
    <title></title>
    <authors>tSQLt-org</authors>
    <owners></owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>tSQLt</description>
  </metadata>
  <files>
    <file src="tSQLt.2019.dacpac" target="tools\tSQLt.2019.dacpac" />
  </files>
</package>
```

**Comment by cagrin** [comment]
Ok, great. Looking forward for new release of tSQLt.
